export const mockPosts = [
  {
    id: "101",
    userId: "1",
    content: "Exploring Wonderland!",
    imageUrl: "https://example.com/wonderland.jpg",
    createdAt: new Date(),
    likesCount: 2,
    likedBy: ["2", "3"],
    comments: [],
  },
  {
    id: "102",
    userId: "2",
    content: "Can we fix it? Yes, we can!",
    createdAt: new Date(),
    likesCount: 1,
    likedBy: ["1"], 
    comments: [],
  },
  {
    id: "103",
    userId: "3",
    content: "Silent movies are a lost art.",
    imageUrl: "https://example.com/charlie.jpg",
    createdAt: new Date(),
    likesCount: 0,
    likedBy: [],
    comments: [],
  },
  {
    id: "104",
    userId: "1",
    content: "Another day in Wonderland!",
    createdAt: new Date(),
    likesCount: 1,
    likedBy: ["2"],
    comments: [],
  },
];
